name: Generate Snake

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate Snake
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ShyamDeepak-03
          outputs: |
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark&color_snake=00ff41&color_dots=#161b22,#003300,#006600,#009900,#00ff41

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: output
          folder: dist
          force: true
